# Generated by Django 3.1 on 2023-02-17 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=30)),
                ('opening', models.CharField(blank=True, max_length=10, null=True)),
                ('spread', models.CharField(blank=True, max_length=10, null=True)),
                ('final', models.BooleanField(default=False)),
                ('home_score', models.PositiveIntegerField(default=0, null=True)),
                ('away_score', models.PositiveIntegerField(default=0, null=True)),
                ('qtr', models.CharField(max_length=25, null=True)),
                ('tie', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('day', models.CharField(blank=True, max_length=10, null=True)),
                ('game_time', models.DateTimeField(blank=True, null=True)),
                ('postponed', models.BooleanField(default=False)),
                ('playoff_picks', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=30)),
                ('ties_lose', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('email_picks', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.league')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayoffPicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rushing_yards', models.PositiveIntegerField(null=True)),
                ('passing_yards', models.PositiveIntegerField(null=True)),
                ('total_points_scored', models.PositiveIntegerField()),
                ('points_on_fg', models.PositiveIntegerField()),
                ('takeaways', models.PositiveIntegerField()),
                ('sacks', models.PositiveIntegerField()),
                ('def_special_teams_tds', models.PositiveIntegerField()),
                ('home_runner', models.PositiveIntegerField()),
                ('home_receiver', models.PositiveIntegerField()),
                ('home_passing', models.PositiveIntegerField(null=True)),
                ('home_passer_rating', models.FloatField(default=100.0)),
                ('away_runner', models.PositiveIntegerField()),
                ('away_receiver', models.PositiveIntegerField()),
                ('away_passing', models.PositiveIntegerField(null=True)),
                ('away_passer_rating', models.FloatField(default=100.0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.games')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=30, unique=True)),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mike_abbr', models.CharField(max_length=4, null=True)),
                ('nfl_abbr', models.CharField(max_length=4, null=True)),
                ('long_name', models.CharField(max_length=30, null=True)),
                ('typo_name', models.CharField(blank=True, max_length=30, null=True)),
                ('typo_name1', models.CharField(blank=True, max_length=30, null=True)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('pic', models.URLField(null=True)),
            ],
            options={
                'ordering': ('nfl_abbr',),
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=30, null=True)),
                ('week', models.PositiveIntegerField()),
                ('game_cnt', models.PositiveIntegerField(null=True)),
                ('current', models.BooleanField(default=False)),
                ('late_picks', models.BooleanField(default=False)),
                ('set_started', models.BooleanField(default=False)),
                ('set_not_started', models.BooleanField(default=False)),
                ('regular_week', models.BooleanField(default=False)),
                ('season_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_app.season')),
            ],
        ),
        migrations.CreateModel(
            name='WeekScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(null=True)),
                ('projected_score', models.PositiveIntegerField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.player')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.week')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonPicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.games')),
                ('pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.teams')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.season')),
            ],
        ),
        migrations.CreateModel(
            name='PlayoffStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rushing_yards', models.IntegerField(null=True)),
                ('passing_yards', models.IntegerField(null=True)),
                ('total_points_scored', models.IntegerField(null=True)),
                ('points_on_fg', models.IntegerField(null=True)),
                ('takeaways', models.IntegerField(null=True)),
                ('sacks', models.IntegerField(null=True)),
                ('def_special_teams_tds', models.IntegerField(null=True)),
                ('home_runner', models.IntegerField(null=True)),
                ('home_receiver', models.IntegerField(null=True)),
                ('home_passing', models.IntegerField(null=True)),
                ('home_passer_rating', models.FloatField(null=True)),
                ('away_runner', models.IntegerField(null=True)),
                ('away_receiver', models.IntegerField(null=True)),
                ('away_passing', models.IntegerField(null=True)),
                ('away_passer_rating', models.FloatField(null=True)),
                ('data', models.JSONField(null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_app.games')),
                ('winning_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_app.teams')),
            ],
        ),
        migrations.CreateModel(
            name='PlayoffScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rushing_yards', models.IntegerField()),
                ('passing_yards', models.IntegerField()),
                ('total_points_scored', models.IntegerField()),
                ('points_on_fg', models.IntegerField()),
                ('takeaways', models.IntegerField()),
                ('sacks', models.IntegerField()),
                ('def_special_teams_tds', models.IntegerField()),
                ('home_runner', models.IntegerField()),
                ('home_receiver', models.IntegerField()),
                ('home_passing', models.IntegerField()),
                ('away_runner', models.IntegerField()),
                ('away_receiver', models.IntegerField()),
                ('away_passing', models.IntegerField()),
                ('winning_team', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('picks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.playoffpicks')),
            ],
        ),
        migrations.AddField(
            model_name='playoffpicks',
            name='winning_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.teams'),
        ),
        migrations.CreateModel(
            name='Picks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_num', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='fb_app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picksteam', to='fb_app.teams')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.week')),
            ],
        ),
        migrations.CreateModel(
            name='PickPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.league')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.season')),
            ],
        ),
        migrations.CreateModel(
            name='PickMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('1', 'player'), ('2', 'favs'), ('3', 'auto'), ('4', 'fixed_auto')], max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.player')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.week')),
            ],
        ),
        migrations.CreateModel(
            name='MikeScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.player')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.week')),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='away',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away', to='fb_app.teams'),
        ),
        migrations.AddField(
            model_name='games',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dog', to='fb_app.teams'),
        ),
        migrations.AddField(
            model_name='games',
            name='fav',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fav', to='fb_app.teams'),
        ),
        migrations.AddField(
            model_name='games',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='fb_app.teams'),
        ),
        migrations.AddField(
            model_name='games',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='fb_app.teams'),
        ),
        migrations.AddField(
            model_name='games',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.week'),
        ),
        migrations.AddField(
            model_name='games',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='fb_app.teams'),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('device_type', models.CharField(blank=True, max_length=100, null=True)),
                ('views', models.PositiveBigIntegerField(default=0, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fb_user', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_app.week')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playoffpicks',
            constraint=models.UniqueConstraint(fields=('player', 'game'), name='duplicate_picks'),
        ),
        migrations.AlterIndexTogether(
            name='picks',
            index_together={('week', 'player')},
        ),
        migrations.AlterIndexTogether(
            name='games',
            index_together={('week', 'home', 'away')},
        ),
    ]
