# Generated by Django 2.0.4 on 2018-09-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='picks',
            index_together={('week', 'player')},
        ),
    ]
