# Generated by Django 5.1 on 2026-03-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fb_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="games",
            unique_together={("week", "home", "away")},
        ),
        migrations.AlterUniqueTogether(
            name="picks",
            unique_together={("week", "player", "team")},
        ),
    ]
