# Generated by Django 2.0.4 on 2019-04-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='qtr',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
