# Generated by Django 5.1 on 2026-09-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0002_alter_games_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='games',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='games',
            name='eid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='games',
            unique_together={('week', 'eid')},
        ),
    ]
