# Generated by Django 2.0.4 on 2018-09-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0002_auto_20180905_2126'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='games',
            index_together={('week', 'home', 'away')},
        ),
    ]
