# Generated by Django 2.0.4 on 2019-08-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0003_auto_20190812_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
