# Generated by Django 2.0.4 on 2019-08-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0005_teams_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='late_picks',
            field=models.BooleanField(default=False),
        ),
    ]
