# Generated by Django 2.0.4 on 2019-09-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0006_week_late_picks'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
