# Generated by Django 2.0.4 on 2019-09-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0007_player_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='ties_lose',
            field=models.BooleanField(default=True),
        ),
    ]
