# Generated by Django 3.1 on 2020-09-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0010_games_game_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='game_day',
            new_name='game_time',
        ),
    ]
