# Generated by Django 3.1 on 2020-09-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0011_auto_20200906_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='set_not_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='week',
            name='set_started',
            field=models.BooleanField(default=False),
        ),
    ]
