# Generated by Django 3.1 on 2020-10-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0013_auto_20201012_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='postponed',
            field=models.BooleanField(default=False),
        ),
    ]
