# Generated by Django 3.1 on 2020-10-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0014_games_postponed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='away_score',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='home_score',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
