# Generated by Django 3.1 on 2020-12-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0015_auto_20201013_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.league')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.season')),
            ],
        ),
    ]
