# Generated by Django 3.1 on 2021-01-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0017_playoffpicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='playoff_picks',
            field=models.BooleanField(default=False),
        ),
    ]
