# Generated by Django 3.1 on 2021-01-04 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0018_games_playoff_picks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayoffStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rushing_yards', models.IntegerField()),
                ('passing_yards', models.IntegerField()),
                ('total_points_scored', models.IntegerField()),
                ('points_on_fg', models.IntegerField()),
                ('takeaways', models.IntegerField()),
                ('sacks', models.IntegerField()),
                ('def_special_teams_tds', models.IntegerField()),
                ('team_one_runner', models.IntegerField()),
                ('team_one_receiver', models.IntegerField()),
                ('team_one_passing', models.IntegerField()),
                ('team_two_runner', models.IntegerField()),
                ('team_two_receiver', models.IntegerField()),
                ('team_two_passing', models.IntegerField()),
                ('picks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.playoffpicks')),
            ],
        ),
        migrations.CreateModel(
            name='PlayoffScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rushing_yards', models.IntegerField()),
                ('passing_yards', models.IntegerField()),
                ('total_points_scored', models.IntegerField()),
                ('points_on_fg', models.IntegerField()),
                ('takeaways', models.IntegerField()),
                ('sacks', models.IntegerField()),
                ('def_special_teams_tds', models.IntegerField()),
                ('team_one_runner', models.IntegerField()),
                ('team_one_receiver', models.IntegerField()),
                ('team_one_passing', models.IntegerField()),
                ('team_two_runner', models.IntegerField()),
                ('team_two_receiver', models.IntegerField()),
                ('team_two_passing', models.IntegerField()),
                ('winning_team', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('picks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.playoffpicks')),
            ],
        ),
    ]
