# Generated by Django 3.1 on 2021-01-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0019_playoffscores_playoffstats'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playoffpicks',
            constraint=models.UniqueConstraint(fields=('player', 'game'), name='duplicate_picks'),
        ),
    ]
