# Generated by Django 3.1 on 2021-01-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0020_auto_20210105_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='playoffscores',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
