# Generated by Django 3.1 on 2021-01-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0025_auto_20210107_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='playoffpicks',
            name='away_passer_rating',
            field=models.PositiveIntegerField(default=100.0),
        ),
        migrations.AddField(
            model_name='playoffpicks',
            name='home_passer_rating',
            field=models.PositiveIntegerField(default=100.0),
        ),
        migrations.AddField(
            model_name='playoffstats',
            name='away_passer_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='playoffstats',
            name='home_passer_rating',
            field=models.FloatField(null=True),
        ),
    ]
