# Generated by Django 3.1 on 2021-01-10 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0026_auto_20210109_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='playoffstats',
            name='winning_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_app.teams'),
        ),
    ]
