# Generated by Django 3.1 on 2021-01-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0027_playoffstats_winning_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playoffpicks',
            name='away_passing',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playoffpicks',
            name='home_passing',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
