# Generated by Django 3.1 on 2021-01-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0028_auto_20210110_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playoffpicks',
            name='passing_yards',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playoffpicks',
            name='rushing_yards',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
