# Generated by Django 4.0 on 2022-08-11 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0030_auto_20210204_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('1', 'player'), ('2', 'random'), ('3', 'auto'), ('4', 'fixed_auto')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.player')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.week')),
            ],
        ),
    ]
