# Generated by Django 4.0 on 2022-08-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0031_pickmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickmethod',
            old_name='user',
            new_name='player',
        ),
        migrations.AlterField(
            model_name='pickmethod',
            name='method',
            field=models.CharField(choices=[('1', 'player'), ('2', 'favs'), ('3', 'auto'), ('4', 'fixed_auto')], max_length=20),
        ),
    ]
