# Generated by Django 4.0 on 2022-09-03 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0034_week_regular_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonPicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.games')),
                ('pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.teams')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.season')),
            ],
        ),
    ]
