# Generated by Django 2.0.4 on 2019-04-23 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('ccy', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=100)),
                ('open_date', models.DateField()),
                ('close_dat', models.DateField(null=True)),
                ('notes', models.CharField(max_length=300)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port_app.MarketData')),
            ],
        ),
    ]
