# Generated by Django 2.0.4 on 2019-06-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_app', '0005_position_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
