# Generated by Django 2.0.4 on 2019-06-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_app', '0006_auto_20190609_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='ccy',
            field=models.CharField(choices=[(1, 'USD'), (2, 'JPY')], max_length=3),
        ),
    ]
