# Generated by Django 2.0.4 on 2019-06-09 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port_app', '0007_auto_20190609_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='status',
        ),
    ]
