# Generated by Django 2.0.4 on 2018-09-04 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('winner_bonus', models.IntegerField(null=True)),
                ('cut_bonus', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=256)),
                ('currentWGR', models.IntegerField(null=True)),
                ('alternate', models.NullBooleanField()),
            ],
            options={
                'ordering': ['group', 'currentWGR'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('playerCnt', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OWGR_name', models.CharField(max_length=256)),
                ('PGA_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Picks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(null=True)),
                ('playerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_app.Field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('player', models.CharField(max_length=256)),
                ('score', models.PositiveIntegerField()),
                ('toPar', models.CharField(max_length=10, null=True)),
                ('today_score', models.CharField(max_length=10, null=True)),
                ('thru', models.CharField(max_length=100, null=True)),
                ('sod_position', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('start_date', models.DateField(null=True)),
                ('field_json_url', models.URLField(null=True)),
                ('score_json_url', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_app.Group'),
        ),
        migrations.AddField(
            model_name='field',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_app.Tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='picks',
            unique_together={('playerName', 'user')},
        ),
    ]
