# Generated by Django 2.0.4 on 2019-03-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
