# Generated by Django 2.0.4 on 2018-10-18 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golf_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTotalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='scoredetails',
            name='player',
        ),
        migrations.AddField(
            model_name='scoredetails',
            name='pick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='golf_app.Picks'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='season',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scoredetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='totalscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklytotalscore',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_app.Tournament'),
        ),
        migrations.AddField(
            model_name='weeklytotalscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
