# Generated by Django 2.0.4 on 2018-10-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0002_auto_20181018_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoredetails',
            name='score',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
