# Generated by Django 2.0.4 on 2018-11-01 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0002_auto_20181029_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picks',
            name='playerName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='golf_app.Field'),
        ),
    ]
