# Generated by Django 2.0.4 on 2018-11-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0003_auto_20181101_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalscore',
            name='cut_count',
            field=models.IntegerField(null=True),
        ),
    ]
