# Generated by Django 2.0.4 on 2019-03-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0004_auto_20190328_2126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mpscores',
            unique_together=set(),
        ),
    ]
