# Generated by Django 2.0.4 on 2019-01-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0004_totalscore_cut_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoredetails',
            name='toPar',
            field=models.IntegerField(null=True),
        ),
    ]
