# Generated by Django 2.0.4 on 2018-10-19 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0004_auto_20181019_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusdetails',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='golf_app.Tournament'),
        ),
        migrations.AddField(
            model_name='totalscore',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='golf_app.Tournament'),
        ),
        migrations.AlterField(
            model_name='field',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_app.Group'),
        ),
    ]
