# Generated by Django 2.0.4 on 2019-03-29 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0005_auto_20190328_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpscores',
            name='pick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick', to='golf_app.Picks'),
        ),
    ]
