# Generated by Django 2.0.4 on 2018-10-19 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0005_auto_20181019_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='golf_app.Group'),
        ),
    ]
