# Generated by Django 2.0.4 on 2019-03-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0006_auto_20190329_1202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mpscores',
            unique_together={('pick', 'round')},
        ),
    ]
