# Generated by Django 2.0.4 on 2019-03-29 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0007_auto_20190329_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpscores',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='golf_app.Field'),
        ),
        migrations.AlterField(
            model_name='mpscores',
            name='pick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='golf_app.Picks'),
        ),
        migrations.AlterUniqueTogether(
            name='mpscores',
            unique_together={('player', 'round')},
        ),
    ]
