# Generated by Django 2.0.4 on 2018-10-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0007_auto_20181019_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalscore',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
