# Generated by Django 2.0.4 on 2019-03-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0008_auto_20190329_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpscores',
            name='pick',
        ),
    ]
