# Generated by Django 2.0.4 on 2018-10-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0008_auto_20181019_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoredetails',
            name='pick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_app.Picks'),
        ),
    ]
