# Generated by Django 2.0.4 on 2019-03-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0009_remove_mpscores_pick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpscores',
            name='round',
            field=models.FloatField(),
        ),
    ]
