# Generated by Django 2.0.4 on 2018-10-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0009_auto_20181019_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
