# Generated by Django 2.0.4 on 2018-10-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0010_tournament_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picks',
            name='score',
        ),
    ]
