# Generated by Django 2.0.4 on 2019-04-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0010_auto_20190331_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoredetails',
            name='toPar',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
