# Generated by Django 2.0.4 on 2018-10-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0011_remove_picks_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='picks',
            name='score',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
