# Generated by Django 2.0.4 on 2019-04-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0012_auto_20190403_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='team',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
