# Generated by Django 2.0.4 on 2018-10-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0012_picks_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='golf_app.Tournament'),
        ),
    ]
