# Generated by Django 2.0.4 on 2018-10-20 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0013_group_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_app.Tournament'),
        ),
    ]
