# Generated by Django 2.0.4 on 2019-04-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0013_field_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='team',
        ),
        migrations.AddField(
            model_name='field',
            name='partner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
