# Generated by Django 2.0.4 on 2018-10-21 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0014_auto_20181020_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('current', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='tournament',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_app.Season'),
        ),
    ]
