# Generated by Django 2.0.4 on 2019-04-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0014_auto_20190423_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='teamID',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
