# Generated by Django 2.0.4 on 2018-10-21 02:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golf_app', '0015_auto_20181021_1058'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklytotalscore',
            unique_together={('tournament', 'user')},
        ),
    ]
