# Generated by Django 2.0.4 on 2019-04-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0016_auto_20190424_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusdetails',
            name='cut_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bonusdetails',
            name='winner_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
