# Generated by Django 2.0.4 on 2018-10-21 02:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golf_app', '0016_auto_20181021_1128'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklytotalscore',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='weeklytotalscore',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='weeklytotalscore',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='totalscore',
            unique_together={('tournament', 'user')},
        ),
        migrations.DeleteModel(
            name='WeeklyTotalScore',
        ),
    ]
