# Generated by Django 2.0.4 on 2018-10-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0017_auto_20181021_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='pga_tournament_num',
            field=models.CharField(default='999', max_length=10),
        ),
    ]
