# Generated by Django 2.0.4 on 2019-05-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0017_auto_20190425_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='picks',
            name='auto',
            field=models.NullBooleanField(default=False),
        ),
    ]
