# Generated by Django 2.0.4 on 2018-10-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0018_tournament_pga_tournament_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='pga_tournament_num',
            field=models.CharField(max_length=10),
        ),
    ]
