# Generated by Django 2.0.4 on 2018-10-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0019_auto_20181022_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoredetails',
            name='pick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='golf_app.Picks'),
        ),
    ]
