# Generated by Django 2.0.4 on 2018-10-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0020_auto_20181023_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picks',
            name='playerName',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='golf_app.Field'),
        ),
    ]
