# Generated by Django 2.0.4 on 2019-09-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0023_auto_20190628_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='major',
            field=models.BooleanField(default=False),
        ),
    ]
