# Generated by Django 2.0.4 on 2019-10-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0024_tournament_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='late_picks',
            field=models.BooleanField(default=False),
        ),
    ]
