# Generated by Django 2.0.4 on 2019-11-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0025_tournament_late_picks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusdetails',
            name='major_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
