# Generated by Django 2.0.4 on 2019-12-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0026_bonusdetails_major_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='seet_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='set_notstarted',
            field=models.BooleanField(default=False),
        ),
    ]
