# Generated by Django 2.0.4 on 2020-01-18 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0026_bonusdetails_major_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGAWebScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('score', models.CharField(max_length=30, null=True)),
                ('r1', models.CharField(max_length=30, null=True)),
                ('r2', models.CharField(max_length=30, null=True)),
                ('r3', models.CharField(max_length=30, null=True)),
                ('r4', models.CharField(max_length=30, null=True)),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_app.Field')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='manual_score_file',
            field=models.BooleanField(default=False),
        ),
       migrations.AddField(
           model_name='tournament',
           name='set_notstarted',
           field=models.BooleanField(default=False),
       ),
       migrations.AddField(
           model_name='tournament',
           name='set_started',
           field=models.BooleanField(default=False),
       ),
        migrations.AddField(
            model_name='pgawebscores',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_app.Tournament'),
        ),
    ]
