# Generated by Django 2.0.4 on 2019-12-31 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0027_auto_20191231_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='seet_started',
            new_name='set_started',
        ),
    ]
