# Generated by Django 2.0.4 on 2020-01-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0027_auto_20200118_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='cut_score',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='score_update_time',
            field=models.DateTimeField(null=True),
        ),
        # migrations.AddField(
        #     model_name='tournament',
        #     name='set_notstarted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='tournament',
        #     name='set_started',
        #     field=models.BooleanField(default=False),
        # ),
    ]
