# Generated by Django 2.0.4 on 2020-02-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0032_auto_20200201_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='has_cut',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='cut_score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='score_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
