# Generated by Django 3.0.3 on 2020-03-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0033_auto_20200209_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='leaders',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
