# Generated by Django 3.0.3 on 2020-03-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0034_tournament_leaders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='leaders',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
