# Generated by Django 3.0.3 on 2020-03-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0036_golfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfer',
            name='flag_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='pic_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
