# Generated by Django 3.0.7 on 2020-07-29 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0037_auto_20200312_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='golfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='golf_app.Golfer'),
        ),
    ]
