# Generated by Django 3.0.7 on 2020-08-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0038_field_golfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='playoff',
            field=models.BooleanField(default=False),
        ),
    ]
