# Generated by Django 3.0.7 on 2020-08-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0039_tournament_playoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
