# Generated by Django 3.1 on 2020-08-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0042_scoredict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='alternate',
            field=models.BooleanField(null=True),
        ),
    ]
