# Generated by Django 3.1 on 2020-08-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0043_auto_20200810_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoredict',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
