# Generated by Django 3.1 on 2020-08-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0046_auto_20200822_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoredetails',
            name='gross_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scoredetails',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
