# Generated by Django 3.1 on 2020-08-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0047_auto_20200831_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picks',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
