# Generated by Django 3.1 on 2020-09-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0048_auto_20200831_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoredict',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_dict', to='golf_app.tournament'),
        ),
    ]
