# Generated by Django 3.1 on 2020-09-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0051_scoredict_pick_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoredict',
            name='cbs_data',
            field=models.JSONField(null=True),
        ),
    ]
