# Generated by Django 3.1 on 2020-09-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0052_scoredict_cbs_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='handi',
            field=models.IntegerField(null=True),
        ),
    ]
