# Generated by Django 3.1 on 2020-10-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0053_field_handi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='saved_cut_num',
            field=models.IntegerField(null=True),
        ),
    ]
