# Generated by Django 3.1 on 2021-01-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0055_auto_20201011_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='cbs_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
