# Generated by Django 3.1 on 2021-01-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0057_auto_20210120_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoredetails',
            name='sod_position',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
