# Generated by Django 3.1 on 2021-02-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0058_auto_20210123_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='prior_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='recent',
            field=models.JSONField(null=True),
        ),
    ]
