# Generated by Django 3.1 on 2021-02-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0059_auto_20210215_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='ignore_name_mismatch',
            field=models.BooleanField(default=False),
        ),
    ]
