# Generated by Django 3.1.7 on 2021-04-20 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0062_tournament_espn_t_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['-tournament', 'group', 'currentWGR']},
        ),
        migrations.AddField(
            model_name='field',
            name='partner_golfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_golfer', to='golf_app.golfer'),
        ),
    ]
