# Generated by Django 3.2.2 on 2021-05-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0066_accesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='season_stats',
            field=models.JSONField(null=True),
        ),
    ]
