# Generated by Django 3.1 on 2021-07-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0074_countrypicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypicks',
            name='gender',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
