# Generated by Django 3.2.2 on 2021-08-22 13:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golf_app', '0076_auto_20210822_1030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bonusdetails',
            unique_together={('tournament', 'user', 'bonus_type')},
        ),
    ]
