# Generated by Django 3.1 on 2021-09-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0080_auto_20210906_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fedexfield',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fedexfield',
            name='soy_owgr',
            field=models.IntegerField(null=True),
        ),
    ]
