# Generated by Django 3.2.2 on 2021-09-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0081_auto_20210907_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypicks',
            name='ryder_cup_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
