# Generated by Django 3.2.2 on 2021-09-24 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0082_countrypicks_ryder_cup_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='RyderCupMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_format', models.CharField(max_length=50)),
                ('match_num', models.CharField(max_length=50)),
                ('data_links', models.JSONField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('winner_score', models.CharField(max_length=10, null=True)),
                ('loser_score', models.CharField(max_length=10, null=True)),
                ('euro_golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='euro_golfer', to='golf_app.field')),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='golf_app.field')),
                ('usa_golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usa_golfer', to='golf_app.field')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='golf_app.field')),
            ],
        ),
    ]
