# Generated by Django 3.2.2 on 2021-09-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0083_rydercupmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusdetails',
            name='bonus_type',
            field=models.CharField(choices=[('1', 'winning golfer'), ('2', 'no cuts'), ('3', 'weekly winner'), ('4', 'playoff'), ('5', 'best in group'), ('6', 'trifecta'), ('7', 'manual'), ('9', 'Ryder Cup winner'), ('10', 'Ryder Cup Score')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.IntegerField(default=0),
        ),
    ]
