# Generated by Django 3.2.2 on 2021-10-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0084_auto_20210930_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='fedex_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
