# Generated by Django 3.2.2 on 2021-11-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0085_tournament_fedex_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoredict',
            name='espn_api_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('espn_api_data', models.JSONField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_app.tournament')),
            ],
        ),
    ]
