# Generated by Django 3.2.9 on 2021-11-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0086_auto_20211107_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='fedexpicks',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
