# Generated by Django 4.0 on 2021-12-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0087_fedexpicks_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='round_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
