# Generated by Django 4.0 on 2022-05-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0088_tournament_round_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='individual_stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickmethod',
            name='method',
            field=models.CharField(choices=[('1', 'player'), ('2', 'random'), ('3', 'auto'), ('4', 'fixed_auto')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='tournament',
            unique_together={('season', 'pga_tournament_num')},
        ),
    ]
