# Generated by Django 4.0 on 2022-08-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0089_tournament_individual_stats_alter_pickmethod_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
