# Generated by Django 4.0 on 2022-09-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0090_season_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='fedexpicks',
            name='top_3',
            field=models.BooleanField(null=True),
        ),
    ]
