# Generated by Django 4.0 on 2023-04-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0092_alter_fedexpicks_top_3'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['season', 'pga_tournament_num'], name='golf_app_to_season__e18779_idx'),
        ),
    ]
