# Generated by Django 4.0 on 2024-01-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0093_tournament_golf_app_to_season__e18779_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
