# Generated by Django 4.0 on 2024-02-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0094_alter_season_season'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tournament',
            name='golf_app_to_season__e18779_idx',
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['season', 'pga_tournament_num', 'start_date'], name='golf_app_to_season__57f577_idx'),
        ),
    ]
