# Generated by Django 4.0 on 2024-04-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0096_remove_tournament_golf_app_to_season__57f577_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='use_saved_cut_num',
            field=models.BooleanField(default=False),
        ),
    ]
