# Generated by Django 4.0 on 2024-04-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0097_tournament_use_saved_cut_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='use_saved_cut_num',
        ),
    ]
