# Generated by Django 5.1 on 2026-03-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0098_remove_tournament_use_saved_cut_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='field_json_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='score_json_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
