# Generated by Django 2.0.4 on 2019-03-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dist', models.FloatField()),
                ('time', models.DurationField()),
                ('cals', models.PositiveIntegerField()),
                ('location', models.CharField(choices=[('1', 'town'), ('2', 'palace'), ('3', 'tamagawa'), ('4', 'tm')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('dist', models.PositiveIntegerField(null=True)),
                ('type', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='run_app.Plan')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='run_app.Run')),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField()),
                ('main_shoe', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='shoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run', to='run_app.Shoes'),
        ),
    ]
