# Generated by Django 2.0.4 on 2018-09-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dist', models.FloatField()),
                ('time', models.DurationField()),
                ('cals', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='shoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run', to='run_app.Shoes'),
        ),
    ]
