# Generated by Django 2.0.4 on 2018-09-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='location',
            field=models.CharField(choices=[('1', 'town'), ('2', 'palace'), ('3', 'tamagawa'), ('4', 'tm')], max_length=30),
        ),
    ]
