# Generated by Django 3.1 on 2020-11-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='type',
            new_name='sched_type',
        ),
    ]
