# Generated by Django 2.0.4 on 2018-09-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_app', '0002_auto_20180911_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='main_shoe',
            field=models.BooleanField(default=False),
        ),
    ]
