# Generated by Django 4.0 on 2023-12-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_app', '0002_auto_20201130_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
