# Generated by Django 5.1 on 2026-09-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_app', '0003_plan_current_plan_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='average_heart_rate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='max_heart_rate',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
