# Generated by Django 2.0.4 on 2018-10-01 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run_app', '0004_plan_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='run_app.Run'),
        ),
    ]
