# Generated by Django 2.0.4 on 2018-10-01 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run_app', '0005_schedule_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='run',
        ),
        migrations.AddField(
            model_name='run',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='run_app.Schedule'),
        ),
    ]
