# Generated by Django 2.0.4 on 2018-10-01 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run_app', '0006_auto_20181001_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='run_app.Schedule'),
        ),
    ]
