# Generated by Django 2.0.4 on 2018-10-01 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run_app', '0007_auto_20181001_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='run_app.Run'),
        ),
    ]
