# Generated by Django 4.0 on 2022-10-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='flag_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
