# Generated by Django 4.0 on 2022-11-14 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankings', models.JSONField(null=True)),
                ('group_data', models.JSONField(null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wc_app.stage')),
            ],
        ),
    ]
