# Generated by Django 4.0 on 2022-11-19 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wc_app', '0002_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wc_app.stage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wc_ts_user', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wc_app.stage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wc_al_user', to='auth.user')),
            ],
        ),
    ]
