# Generated by Django 4.0 on 2022-10-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0002_team_flag_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='info_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
