# Generated by Django 4.0 on 2022-10-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0003_team_info_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
