# Generated by Django 4.0 on 2022-11-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0004_alter_accesslog_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalscore',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
