# Generated by Django 4.0 on 2022-11-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0005_picks_rank_picks_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='set_not_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='set_started',
            field=models.BooleanField(default=False),
        ),
    ]
