# Generated by Django 4.0 on 2022-11-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0005_alter_totalscore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='score_url',
            field=models.URLField(null=True),
        ),
    ]
