# Generated by Django 4.0 on 2022-11-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0006_stage_score_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='display_data',
            field=models.JSONField(null=True),
        ),
    ]
