# Generated by Django 4.0 on 2022-11-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0007_data_display_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='force_refresh',
            field=models.BooleanField(default=False),
        ),
    ]
