# Generated by Django 4.0 on 2022-11-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0008_data_force_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='display_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='group_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='rankings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
