# Generated by Django 4.0 on 2022-11-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0009_alter_data_display_data_alter_data_group_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picks',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
