# Generated by Django 3.1 on 2023-02-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0011_auto_20230216_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo_file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
