# Generated by Django 3.1 on 2023-02-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0012_event_logo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
