# Generated by Django 3.1 on 2023-02-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0013_auto_20230217_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo_file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
