# Generated by Django 3.1 on 2023-02-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0014_auto_20230217_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
