# Generated by Django 4.0 on 2023-03-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0016_alter_accesslog_id_alter_data_id_alter_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='early_game',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
