# Generated by Django 4.0 on 2023-03-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app', '0017_team_early_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='early_picks_period',
            field=models.BooleanField(default=False),
        ),
    ]
