# Generated by Django 5.1 on 2026-03-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wc_app", "0018_stage_early_picks_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(default="wc", max_length=100),
        ),
    ]
